### ISSUE TITLE
error in trajectory analysis

### ISSUE THREAD

**Issue by biotech70** [lkagami/geo_measures_pymol#2]
HI. during gromacs trajectory analysis i get below error.  i use from pymol 2.3 in Ubuntu 20.04.1. please guide me.

![error](https://user-images.githubusercontent.com/73783725/105606388-4d72e480-5dae-11eb-958c-6be28daad4b4.png)

**Comment by lkagami** [comment]
Dear user,
Thank you for use Geo-measures! Please install the mdtraj package using pip or conda install command. 
Regards,
Luciano

**Comment by negin-safaee** [comment]
Hello , during gromacs trajectory analysis i get below error and i can not get the final plots, i am using  pymol  in Ubuntu 20.04.1.  and i have installed pandas matplotlib scipy mdtraj sklearn packages , please guide me to solve this problem.
Thanks a lot
geo_measures_pymol-master/__init__.py", line 778, in run
    g_data =  pd.DataFrame()
NameError: free variable 'pd' referenced before assignment in enclosing scope
