### ISSUE TITLE
error

### ISSUE THREAD

**Issue by negSA1** [lkagami/geo_measures_pymol#3]
Hello , during gromacs trajectory analysis i get below error and i can not get the final plots, i am using pymol in Ubuntu 20.04.1. and i have installed pandas matplotlib scipy mdtraj sklearn packages , please guide me to solve this problem.
Thanks a lot
geo_measures_pymol-master/init.py", line 778, in run
g_data = pd.DataFrame()
NameError: free variable 'pd' referenced before assignment in enclosing scope

**Comment by lkagami** [comment]
Dear user,
Please, send me all error terminal lines. Thank you for use Geo-measures.

**Comment by negSA1** [comment]
Thanks for your quick response
when i use PCA i got this error : 
PyMOL(TM) 2.5.2 - Incentive Product
 Copyright (C) Schrodinger, LLC
 
 This Executable Build integrates and extends Open-Source PyMOL.
No License File - For Evaluation Only (29 days remaining)
 Detected OpenGL version 4.1. Shaders available.
 Geometry shaders not available
 Detected GLSL version 4.10.
 OpenGL graphics engine:
  GL_VENDOR:   VMware, Inc.
  GL_RENDERER: SVGA3D; build: RELEASE;  LLVM;
  GL_VERSION:  4.1 (Compatibility Profile) Mesa 21.0.3
 Detected 4 CPU cores.  Enabled multithreaded rendering.
 Warning: 'model' is a reserved keyword, appending underscore
 CmdLoad: "/home/safaei/Downloads/rbd-omicron-30/model.gro" loaded as "model_".
PyMOL>set defer_builds_mode, 3
 Setting: defer_builds_mode set to 3.
PyMOL>load_traj \
PyMOL>    /home/safaei/Downloads/rbd-omicron-30/protein.xtc, \
PyMOL>    model_, 1, \
PyMOL>    start=1, stop=-1, interval=1
 ObjectMolecule: read set 1 into state 1...
 ObjectMolecule: read set 2 into state 2...
 ObjectMolecule: read set 3 into state 3...
 ObjectMolecule: read set 4 into state 4...
 ObjectMolecule: read set 5 into state 5...
 ObjectMolecule: read set 6 into state 6...
 ObjectMolecule: read set 7 into state 7...
 ObjectMolecule: read set 8 into state 8...
 ObjectMolecule: read set 9 into state 9...
 ObjectMolecule: read set 10 into state 10...
 ObjectMolecule: read set 11 into state 11...
 ObjectMolecule: read set 12 into state 12...
 ObjectMolecule: read set 13 into state 13...
 ObjectMolecule: read set 14 into state 14...
 ObjectMolecule: read set 15 into state 15...
 ObjectMolecule: read set 16 into state 16...
 ObjectMolecule: read set 17 into state 17...
 ObjectMolecule: read set 18 into state 18...
 ObjectMolecule: read set 19 into state 19...
 ObjectMolecule: read set 20 into state 20...
 ObjectMolecule: read set 21 into state 21...
 ObjectMolecule: read set 22 into state 22...
 ObjectMolecule: read set 23 into state 23...
 ObjectMolecule: read set 24 into state 24...
 ObjectMolecule: read set 25 into state 25...
 ObjectMolecule: read set 26 into state 26...
 ObjectMolecule: read set 27 into state 27...
 ObjectMolecule: read set 28 into state 28...
 ObjectMolecule: read set 29 into state 29...
 ObjectMolecule: read set 30 into state 30...
 ObjectMolecule: read set 31 into state 31...
 ObjectMolecule: read set 32 into state 32...
 ObjectMolecule: read set 33 into state 33...
 ObjectMolecule: read set 34 into state 34...
 ObjectMolecule: read set 35 into state 35...
 ObjectMolecule: read set 36 into state 36...
 ObjectMolecule: read set 37 into state 37...
 ObjectMolecule: read set 38 into state 38...
 ObjectMolecule: read set 39 into state 39...
 ObjectMolecule: read set 40 into state 40...
 ObjectMolecule: read set 41 into state 41...
 ObjectMolecule: read set 42 into state 42...
 ObjectMolecule: read set 43 into state 43...
 ObjectMolecule: read set 44 into state 44...
 ObjectMolecule: read set 45 into state 45...
 ObjectMolecule: read set 46 into state 46...
 ObjectMolecule: read set 47 into state 47...
 ObjectMolecule: read set 48 into state 48...
 ObjectMolecule: read set 49 into state 49...
 ObjectMolecule: read set 50 into state 50...
 ObjectMolecule: read set 51 into state 51...
 ObjectMolecule: read set 52 into state 52...
 ObjectMolecule: read set 53 into state 53...
 ObjectMolecule: read set 54 into state 54...
 ObjectMolecule: read set 55 into state 55...
 ObjectMolecule: read set 56 into state 56...
 ObjectMolecule: read set 57 into state 57...
 ObjectMolecule: read set 58 into state 58...
 ObjectMolecule: read set 59 into state 59...
 ObjectMolecule: read set 60 into state 60...
 ObjectMolecule: read set 61 into state 61...
 ObjectMolecule: read set 62 into state 62...
 ObjectMolecule: read set 63 into state 63...
 ObjectMolecule: read set 64 into state 64...
 ObjectMolecule: read set 65 into state 65...
 ObjectMolecule: read set 66 into state 66...
 ObjectMolecule: read set 67 into state 67...
 ObjectMolecule: read set 68 into state 68...
 ObjectMolecule: read set 69 into state 69...
 ObjectMolecule: read set 70 into state 70...
 ObjectMolecule: read set 71 into state 71...
 ObjectMolecule: read set 72 into state 72...
 ObjectMolecule: read set 73 into state 73...
 ObjectMolecule: read set 74 into state 74...
 ObjectMolecule: read set 75 into state 75...
 ObjectMolecule: read set 76 into state 76...
 ObjectMolecule: read set 77 into state 77...
 ObjectMolecule: read set 78 into state 78...
 ObjectMolecule: read set 79 into state 79...
 ObjectMolecule: read set 80 into state 80...
 ObjectMolecule: read set 81 into state 81...
 ObjectMolecule: read set 82 into state 82...
 ObjectMolecule: read set 83 into state 83...
 ObjectMolecule: read set 84 into state 84...
 ObjectMolecule: read set 85 into state 85...
 ObjectMolecule: read set 86 into state 86...
 ObjectMolecule: read set 87 into state 87...
 ObjectMolecule: read set 88 into state 88...
 ObjectMolecule: read set 89 into state 89...
 ObjectMolecule: read set 90 into state 90...
 ObjectMolecule: read set 91 into state 91...
 ObjectMolecule: read set 92 into state 92...
 ObjectMolecule: read set 93 into state 93...
 ObjectMolecule: read set 94 into state 94...
 ObjectMolecule: read set 95 into state 95...
 ObjectMolecule: read set 96 into state 96...
 ObjectMolecule: read set 97 into state 97...
 ObjectMolecule: read set 98 into state 98...
 ObjectMolecule: read set 99 into state 99...
 ObjectMolecule: read set 100 into state 100...
 ObjectMolecule: read set 101 into state 101...
 ObjectMolecule: read set 102 into state 102...
 ObjectMolecule: read set 103 into state 103...
 ObjectMolecule: read set 104 into state 104...
 ObjectMolecule: read set 105 into state 105...
 ObjectMolecule: read set 106 into state 106...
 ObjectMolecule: read set 107 into state 107...
 ObjectMolecule: read set 108 into state 108...
 ObjectMolecule: read set 109 into state 109...
 ObjectMolecule: read set 110 into state 110...
 ObjectMolecule: read set 111 into state 111...
 ObjectMolecule: read set 112 into state 112...
 ObjectMolecule: read set 113 into state 113...
 ObjectMolecule: read set 114 into state 114...
 ObjectMolecule: read set 115 into state 115...
 ObjectMolecule: read set 116 into state 116...
 ObjectMolecule: read set 117 into state 117...
 ObjectMolecule: read set 118 into state 118...
 ObjectMolecule: read set 119 into state 119...
 ObjectMolecule: read set 120 into state 120...
 ObjectMolecule: read set 121 into state 121...
 ObjectMolecule: read set 122 into state 122...
 ObjectMolecule: read set 123 into state 123...
 ObjectMolecule: read set 124 into state 124...
 ObjectMolecule: read set 125 into state 125...
 ObjectMolecule: read set 126 into state 126...
 ObjectMolecule: read set 127 into state 127...
 ObjectMolecule: read set 128 into state 128...
 ObjectMolecule: read set 129 into state 129...
 ObjectMolecule: read set 130 into state 130...
 ObjectMolecule: read set 131 into state 131...
 ObjectMolecule: read set 132 into state 132...
 ObjectMolecule: read set 133 into state 133...
 ObjectMolecule: read set 134 into state 134...
 ObjectMolecule: read set 135 into state 135...
 ObjectMolecule: read set 136 into state 136...
 ObjectMolecule: read set 137 into state 137...
 ObjectMolecule: read set 138 into state 138...
 ObjectMolecule: read set 139 into state 139...
 ObjectMolecule: read set 140 into state 140...
 ObjectMolecule: read set 141 into state 141...
 ObjectMolecule: read set 142 into state 142...
 ObjectMolecule: read set 143 into state 143...
 ObjectMolecule: read set 144 into state 144...
 ObjectMolecule: read set 145 into state 145...
 ObjectMolecule: read set 146 into state 146...
 ObjectMolecule: read set 147 into state 147...
 ObjectMolecule: read set 148 into state 148...
 ObjectMolecule: read set 149 into state 149...
 ObjectMolecule: read set 150 into state 150...
 ObjectMolecule: read set 151 into state 151...
 ObjectMolecule: read set 152 into state 152...
 ObjectMolecule: read set 153 into state 153...
 ObjectMolecule: read set 154 into state 154...
 ObjectMolecule: read set 155 into state 155...
 ObjectMolecule: read set 156 into state 156...
 ObjectMolecule: read set 157 into state 157...
 ObjectMolecule: read set 158 into state 158...
 ObjectMolecule: read set 159 into state 159...
 ObjectMolecule: read set 160 into state 160...
 ObjectMolecule: read set 161 into state 161...
 ObjectMolecule: read set 162 into state 162...
 ObjectMolecule: read set 163 into state 163...
 ObjectMolecule: read set 164 into state 164...
 ObjectMolecule: read set 165 into state 165...
 ObjectMolecule: read set 166 into state 166...
 ObjectMolecule: read set 167 into state 167...
 ObjectMolecule: read set 168 into state 168...
 ObjectMolecule: read set 169 into state 169...
 ObjectMolecule: read set 170 into state 170...
 ObjectMolecule: read set 171 into state 171...
 ObjectMolecule: read set 172 into state 172...
 ObjectMolecule: read set 173 into state 173...
 ObjectMolecule: read set 174 into state 174...
 ObjectMolecule: read set 175 into state 175...
 ObjectMolecule: read set 176 into state 176...
 ObjectMolecule: read set 177 into state 177...
 ObjectMolecule: read set 178 into state 178...
 ObjectMolecule: read set 179 into state 179...
 ObjectMolecule: read set 180 into state 180...
 ObjectMolecule: read set 181 into state 181...
 ObjectMolecule: read set 182 into state 182...
 ObjectMolecule: read set 183 into state 183...
 ObjectMolecule: read set 184 into state 184...
 ObjectMolecule: read set 185 into state 185...
 ObjectMolecule: read set 186 into state 186...
 ObjectMolecule: read set 187 into state 187...
 ObjectMolecule: read set 188 into state 188...
 ObjectMolecule: read set 189 into state 189...
 ObjectMolecule: read set 190 into state 190...
 ObjectMolecule: read set 191 into state 191...
 ObjectMolecule: read set 192 into state 192...
 ObjectMolecule: read set 193 into state 193...
 ObjectMolecule: read set 194 into state 194...
 ObjectMolecule: read set 195 into state 195...
 ObjectMolecule: read set 196 into state 196...
 ObjectMolecule: read set 197 into state 197...
 ObjectMolecule: read set 198 into state 198...
 ObjectMolecule: read set 199 into state 199...
 ObjectMolecule: read set 200 into state 200...
 ObjectMolecule: read set 201 into state 201...
 ObjectMolecule: read set 202 into state 202...
 ObjectMolecule: read set 203 into state 203...
 ObjectMolecule: read set 204 into state 204...
 ObjectMolecule: read set 205 into state 205...
 ObjectMolecule: read set 206 into state 206...
 ObjectMolecule: read set 207 into state 207...
 ObjectMolecule: read set 208 into state 208...
 ObjectMolecule: read set 209 into state 209...
 ObjectMolecule: read set 210 into state 210...
 ObjectMolecule: read set 211 into state 211...
 ObjectMolecule: read set 212 into state 212...
 ObjectMolecule: read set 213 into state 213...
 ObjectMolecule: read set 214 into state 214...
 ObjectMolecule: read set 215 into state 215...
 ObjectMolecule: read set 216 into state 216...
 ObjectMolecule: read set 217 into state 217...
 ObjectMolecule: read set 218 into state 218...
 ObjectMolecule: read set 219 into state 219...
 ObjectMolecule: read set 220 into state 220...
 ObjectMolecule: read set 221 into state 221...
 ObjectMolecule: read set 222 into state 222...
 ObjectMolecule: read set 223 into state 223...
 ObjectMolecule: read set 224 into state 224...
 ObjectMolecule: read set 225 into state 225...
 ObjectMolecule: read set 226 into state 226...
 ObjectMolecule: read set 227 into state 227...
 ObjectMolecule: read set 228 into state 228...
 ObjectMolecule: read set 229 into state 229...
 ObjectMolecule: read set 230 into state 230...
 ObjectMolecule: read set 231 into state 231...
 ObjectMolecule: read set 232 into state 232...
 ObjectMolecule: read set 233 into state 233...
 ObjectMolecule: read set 234 into state 234...
 ObjectMolecule: read set 235 into state 235...
 ObjectMolecule: read set 236 into state 236...
 ObjectMolecule: read set 237 into state 237...
 ObjectMolecule: read set 238 into state 238...
 ObjectMolecule: read set 239 into state 239...
 ObjectMolecule: read set 240 into state 240...
 ObjectMolecule: read set 241 into state 241...
 ObjectMolecule: read set 242 into state 242...
 ObjectMolecule: read set 243 into state 243...
 ObjectMolecule: read set 244 into state 244...
 ObjectMolecule: read set 245 into state 245...
 ObjectMolecule: read set 246 into state 246...
 ObjectMolecule: read set 247 into state 247...
 ObjectMolecule: read set 248 into state 248...
 ObjectMolecule: read set 249 into state 249...
 ObjectMolecule: read set 250 into state 250...
 ObjectMolecule: read set 251 into state 251...
Undo has been disabled. Reason: Object is too large

Change current name ['model_'] by "md"
Change current name ['md'] by "md"
Traceback (most recent call last):
  File "/home/safaei/Downloads/pymol/lib/python3.7/site-packages/pmg_tk/startup/geo_measures_pymol-master/__init__.py", line 700, in run
    traj = mdtraj.load(TRAJ_PATH)
NameError: free variable 'mdtraj' referenced before assignment in enclosing scope 
 
And for Pincer angle i got this error : 
 This Executable Build integrates and extends Open-Source PyMOL.
No License File - For Evaluation Only (29 days remaining)
 Detected OpenGL version 4.1. Shaders available.
 Geometry shaders not available
 Detected GLSL version 4.10.
 OpenGL graphics engine:
  GL_VENDOR:   VMware, Inc.
  GL_RENDERER: SVGA3D; build: RELEASE;  LLVM;
  GL_VERSION:  4.1 (Compatibility Profile) Mesa 21.0.3
 Detected 4 CPU cores.  Enabled multithreaded rendering.
 Warning: 'model' is a reserved keyword, appending underscore
 CmdLoad: "/home/safaei/Downloads/rbd-omicron-30/model.gro" loaded as "model_".
PyMOL>set defer_builds_mode, 3
 Setting: defer_builds_mode set to 3.
PyMOL>load_traj \
PyMOL>    /home/safaei/Downloads/rbd-omicron-30/protein.xtc, \
PyMOL>    model_, 1, \
PyMOL>    start=1, stop=-1, interval=1
 ObjectMolecule: read set 1 into state 1...
 ObjectMolecule: read set 2 into state 2...
 ObjectMolecule: read set 3 into state 3...
 ObjectMolecule: read set 4 into state 4...
 ObjectMolecule: read set 5 into state 5...
 ObjectMolecule: read set 6 into state 6...
 ObjectMolecule: read set 7 into state 7...
 ObjectMolecule: read set 8 into state 8...
 ObjectMolecule: read set 9 into state 9...
 ObjectMolecule: read set 10 into state 10...
 ObjectMolecule: read set 11 into state 11...
 ObjectMolecule: read set 12 into state 12...
 ObjectMolecule: read set 13 into state 13...
 ObjectMolecule: read set 14 into state 14...
 ObjectMolecule: read set 15 into state 15...
 ObjectMolecule: read set 16 into state 16...
 ObjectMolecule: read set 17 into state 17...
 ObjectMolecule: read set 18 into state 18...
 ObjectMolecule: read set 19 into state 19...
 ObjectMolecule: read set 20 into state 20...
 ObjectMolecule: read set 21 into state 21...
 ObjectMolecule: read set 22 into state 22...
 ObjectMolecule: read set 23 into state 23...
 ObjectMolecule: read set 24 into state 24...
 ObjectMolecule: read set 25 into state 25...
 ObjectMolecule: read set 26 into state 26...
 ObjectMolecule: read set 27 into state 27...
 ObjectMolecule: read set 28 into state 28...
 ObjectMolecule: read set 29 into state 29...
 ObjectMolecule: read set 30 into state 30...
 ObjectMolecule: read set 31 into state 31...
 ObjectMolecule: read set 32 into state 32...
 ObjectMolecule: read set 33 into state 33...
 ObjectMolecule: read set 34 into state 34...
 ObjectMolecule: read set 35 into state 35...
 ObjectMolecule: read set 36 into state 36...
 ObjectMolecule: read set 37 into state 37...
 ObjectMolecule: read set 38 into state 38...
 ObjectMolecule: read set 39 into state 39...
 ObjectMolecule: read set 40 into state 40...
 ObjectMolecule: read set 41 into state 41...
 ObjectMolecule: read set 42 into state 42...
 ObjectMolecule: read set 43 into state 43...
 ObjectMolecule: read set 44 into state 44...
 ObjectMolecule: read set 45 into state 45...
 ObjectMolecule: read set 46 into state 46...
 ObjectMolecule: read set 47 into state 47...
 ObjectMolecule: read set 48 into state 48...
 ObjectMolecule: read set 49 into state 49...
 ObjectMolecule: read set 50 into state 50...
 ObjectMolecule: read set 51 into state 51...
 ObjectMolecule: read set 52 into state 52...
 ObjectMolecule: read set 53 into state 53...
 ObjectMolecule: read set 54 into state 54...
 ObjectMolecule: read set 55 into state 55...
 ObjectMolecule: read set 56 into state 56...
 ObjectMolecule: read set 57 into state 57...
 ObjectMolecule: read set 58 into state 58...
 ObjectMolecule: read set 59 into state 59...
 ObjectMolecule: read set 60 into state 60...
 ObjectMolecule: read set 61 into state 61...
 ObjectMolecule: read set 62 into state 62...
 ObjectMolecule: read set 63 into state 63...
 ObjectMolecule: read set 64 into state 64...
 ObjectMolecule: read set 65 into state 65...
 ObjectMolecule: read set 66 into state 66...
 ObjectMolecule: read set 67 into state 67...
 ObjectMolecule: read set 68 into state 68...
 ObjectMolecule: read set 69 into state 69...
 ObjectMolecule: read set 70 into state 70...
 ObjectMolecule: read set 71 into state 71...
 ObjectMolecule: read set 72 into state 72...
 ObjectMolecule: read set 73 into state 73...
 ObjectMolecule: read set 74 into state 74...
 ObjectMolecule: read set 75 into state 75...
 ObjectMolecule: read set 76 into state 76...
 ObjectMolecule: read set 77 into state 77...
 ObjectMolecule: read set 78 into state 78...
 ObjectMolecule: read set 79 into state 79...
 ObjectMolecule: read set 80 into state 80...
 ObjectMolecule: read set 81 into state 81...
 ObjectMolecule: read set 82 into state 82...
 ObjectMolecule: read set 83 into state 83...
 ObjectMolecule: read set 84 into state 84...
 ObjectMolecule: read set 85 into state 85...
 ObjectMolecule: read set 86 into state 86...
 ObjectMolecule: read set 87 into state 87...
 ObjectMolecule: read set 88 into state 88...
 ObjectMolecule: read set 89 into state 89...
 ObjectMolecule: read set 90 into state 90...
 ObjectMolecule: read set 91 into state 91...
 ObjectMolecule: read set 92 into state 92...
 ObjectMolecule: read set 93 into state 93...
 ObjectMolecule: read set 94 into state 94...
 ObjectMolecule: read set 95 into state 95...
 ObjectMolecule: read set 96 into state 96...
 ObjectMolecule: read set 97 into state 97...
 ObjectMolecule: read set 98 into state 98...
 ObjectMolecule: read set 99 into state 99...
 ObjectMolecule: read set 100 into state 100...
 ObjectMolecule: read set 101 into state 101...
 ObjectMolecule: read set 102 into state 102...
 ObjectMolecule: read set 103 into state 103...
 ObjectMolecule: read set 104 into state 104...
 ObjectMolecule: read set 105 into state 105...
 ObjectMolecule: read set 106 into state 106...
 ObjectMolecule: read set 107 into state 107...
 ObjectMolecule: read set 108 into state 108...
 ObjectMolecule: read set 109 into state 109...
 ObjectMolecule: read set 110 into state 110...
 ObjectMolecule: read set 111 into state 111...
 ObjectMolecule: read set 112 into state 112...
 ObjectMolecule: read set 113 into state 113...
 ObjectMolecule: read set 114 into state 114...
 ObjectMolecule: read set 115 into state 115...
 ObjectMolecule: read set 116 into state 116...
 ObjectMolecule: read set 117 into state 117...
 ObjectMolecule: read set 118 into state 118...
 ObjectMolecule: read set 119 into state 119...
 ObjectMolecule: read set 120 into state 120...
 ObjectMolecule: read set 121 into state 121...
 ObjectMolecule: read set 122 into state 122...
 ObjectMolecule: read set 123 into state 123...
 ObjectMolecule: read set 124 into state 124...
 ObjectMolecule: read set 125 into state 125...
 ObjectMolecule: read set 126 into state 126...
 ObjectMolecule: read set 127 into state 127...
 ObjectMolecule: read set 128 into state 128...
 ObjectMolecule: read set 129 into state 129...
 ObjectMolecule: read set 130 into state 130...
 ObjectMolecule: read set 131 into state 131...
 ObjectMolecule: read set 132 into state 132...
 ObjectMolecule: read set 133 into state 133...
 ObjectMolecule: read set 134 into state 134...
 ObjectMolecule: read set 135 into state 135...
 ObjectMolecule: read set 136 into state 136...
 ObjectMolecule: read set 137 into state 137...
 ObjectMolecule: read set 138 into state 138...
 ObjectMolecule: read set 139 into state 139...
 ObjectMolecule: read set 140 into state 140...
 ObjectMolecule: read set 141 into state 141...
 ObjectMolecule: read set 142 into state 142...
 ObjectMolecule: read set 143 into state 143...
 ObjectMolecule: read set 144 into state 144...
 ObjectMolecule: read set 145 into state 145...
 ObjectMolecule: read set 146 into state 146...
 ObjectMolecule: read set 147 into state 147...
 ObjectMolecule: read set 148 into state 148...
 ObjectMolecule: read set 149 into state 149...
 ObjectMolecule: read set 150 into state 150...
 ObjectMolecule: read set 151 into state 151...
 ObjectMolecule: read set 152 into state 152...
 ObjectMolecule: read set 153 into state 153...
 ObjectMolecule: read set 154 into state 154...
 ObjectMolecule: read set 155 into state 155...
 ObjectMolecule: read set 156 into state 156...
 ObjectMolecule: read set 157 into state 157...
 ObjectMolecule: read set 158 into state 158...
 ObjectMolecule: read set 159 into state 159...
 ObjectMolecule: read set 160 into state 160...
 ObjectMolecule: read set 161 into state 161...
 ObjectMolecule: read set 162 into state 162...
 ObjectMolecule: read set 163 into state 163...
 ObjectMolecule: read set 164 into state 164...
 ObjectMolecule: read set 165 into state 165...
 ObjectMolecule: read set 166 into state 166...
 ObjectMolecule: read set 167 into state 167...
 ObjectMolecule: read set 168 into state 168...
 ObjectMolecule: read set 169 into state 169...
 ObjectMolecule: read set 170 into state 170...
 ObjectMolecule: read set 171 into state 171...
 ObjectMolecule: read set 172 into state 172...
 ObjectMolecule: read set 173 into state 173...
 ObjectMolecule: read set 174 into state 174...
 ObjectMolecule: read set 175 into state 175...
 ObjectMolecule: read set 176 into state 176...
 ObjectMolecule: read set 177 into state 177...
 ObjectMolecule: read set 178 into state 178...
 ObjectMolecule: read set 179 into state 179...
 ObjectMolecule: read set 180 into state 180...
 ObjectMolecule: read set 181 into state 181...
 ObjectMolecule: read set 182 into state 182...
 ObjectMolecule: read set 183 into state 183...
 ObjectMolecule: read set 184 into state 184...
 ObjectMolecule: read set 185 into state 185...
 ObjectMolecule: read set 186 into state 186...
 ObjectMolecule: read set 187 into state 187...
 ObjectMolecule: read set 188 into state 188...
 ObjectMolecule: read set 189 into state 189...
 ObjectMolecule: read set 190 into state 190...
 ObjectMolecule: read set 191 into state 191...
 ObjectMolecule: read set 192 into state 192...
 ObjectMolecule: read set 193 into state 193...
 ObjectMolecule: read set 194 into state 194...
 ObjectMolecule: read set 195 into state 195...
 ObjectMolecule: read set 196 into state 196...
 ObjectMolecule: read set 197 into state 197...
 ObjectMolecule: read set 198 into state 198...
 ObjectMolecule: read set 199 into state 199...
 ObjectMolecule: read set 200 into state 200...
 ObjectMolecule: read set 201 into state 201...
 ObjectMolecule: read set 202 into state 202...
 ObjectMolecule: read set 203 into state 203...
 ObjectMolecule: read set 204 into state 204...
 ObjectMolecule: read set 205 into state 205...
 ObjectMolecule: read set 206 into state 206...
 ObjectMolecule: read set 207 into state 207...
 ObjectMolecule: read set 208 into state 208...
 ObjectMolecule: read set 209 into state 209...
 ObjectMolecule: read set 210 into state 210...
 ObjectMolecule: read set 211 into state 211...
 ObjectMolecule: read set 212 into state 212...
 ObjectMolecule: read set 213 into state 213...
 ObjectMolecule: read set 214 into state 214...
 ObjectMolecule: read set 215 into state 215...
 ObjectMolecule: read set 216 into state 216...
 ObjectMolecule: read set 217 into state 217...
 ObjectMolecule: read set 218 into state 218...
 ObjectMolecule: read set 219 into state 219...
 ObjectMolecule: read set 220 into state 220...
 ObjectMolecule: read set 221 into state 221...
 ObjectMolecule: read set 222 into state 222...
 ObjectMolecule: read set 223 into state 223...
 ObjectMolecule: read set 224 into state 224...
 ObjectMolecule: read set 225 into state 225...
 ObjectMolecule: read set 226 into state 226...
 ObjectMolecule: read set 227 into state 227...
 ObjectMolecule: read set 228 into state 228...
 ObjectMolecule: read set 229 into state 229...
 ObjectMolecule: read set 230 into state 230...
 ObjectMolecule: read set 231 into state 231...
 ObjectMolecule: read set 232 into state 232...
 ObjectMolecule: read set 233 into state 233...
 ObjectMolecule: read set 234 into state 234...
 ObjectMolecule: read set 235 into state 235...
 ObjectMolecule: read set 236 into state 236...
 ObjectMolecule: read set 237 into state 237...
 ObjectMolecule: read set 238 into state 238...
 ObjectMolecule: read set 239 into state 239...
 ObjectMolecule: read set 240 into state 240...
 ObjectMolecule: read set 241 into state 241...
 ObjectMolecule: read set 242 into state 242...
 ObjectMolecule: read set 243 into state 243...
 ObjectMolecule: read set 244 into state 244...
 ObjectMolecule: read set 245 into state 245...
 ObjectMolecule: read set 246 into state 246...
 ObjectMolecule: read set 247 into state 247...
 ObjectMolecule: read set 248 into state 248...
 ObjectMolecule: read set 249 into state 249...
 ObjectMolecule: read set 250 into state 250...
 ObjectMolecule: read set 251 into state 251...
Undo has been disabled. Reason: Object is too large

Change current name ['model_'] by "md"
Traceback (most recent call last):
  File "/home/safaei/Downloads/pymol/lib/python3.7/site-packages/pmg_tk/startup/geo_measures_pymol-master/__init__.py", line 522, in run
    g_data =  pd.DataFrame()
NameError: free variable 'pd' referenced before assignment in enclosing scope
 And every time a Note appears : 
Please install python library requeriments: pandas matplotlib, scipy, mdtraj, sklearn
and i click on OK 
but i have installed them by this command :pip install pandas matplotlib scipy mdtraj sklearn

**Comment by lkagami** [comment]
Hi,
So, looks like pymol is not installed in the same python path as the libraries.  To resolve this, download the Anaconda python 3 package and use the command: "conda install -c conda-forge pymol-open-source" to install.  Then use "pip install pandas matplotlib scipy mdtraj sklearn" to install the dependencies.
Regards,
Luciano

**Comment by negSA1** [comment]
Hi
I am so thankful that you helped me to solve the problems. I used the commands that you said and it worked and now i can get results and plots.
I just want to ask how can i use FFL ? because a notice appears : Gromacs should be installed, but i have installed it before. 
I would be thankful if you could guide me?
Thanks a lot
Best regards
safaee

**Comment by lkagami** [comment]
It's necessary to install the GROMACS package.  Type "sudo apt install gromacs" for this. 
Regards,

**Comment by negSA1** [comment]
I am really thankful that you helped me to solve the problem. 

Best regards
safaee

**Comment by lkagami** [comment]
Thank you for use Geo-measures. 
Regards,
