### ISSUE TITLE
Is there any document?

### ISSUE THREAD

**Issue by wonwill** [lkagami/geo_measures_pymol#4]
Hi,

I am a newbie for Geo_Measures which enables me to analyze FEL.
I successfully installed the plugin in PyMOL.
But I can't find any manual or youtube (https://youtu.be/YKmIcU5weI0) about the input files for FEL.
Could you help me with this issue, such as your or any blogs, or documents?

Thanks a lot.

**Comment by lkagami** [comment]
Dear user,
For enable FEL function, it's necessary to install Gromacs package.
Thank you for use Geo-measures,
Luciano
________________________________
From: Won Gi Yoo ***@***.***>
Sent: Wednesday, September 21, 2022 8:07:56 PM
To: lkagami/geo_measures_pymol ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [lkagami/geo_measures_pymol] Is there any document? (Issue #4)


Hi,

I am a newbie for Geo_Measures which enables me to analyze FEL.
I successfully installed the plugin in PyMOL.
But I can't find any manual or youtube (https://youtu.be/YKmIcU5weI0) about the input files for FEL.
Could you help me with this issue, such as your or any blogs, or documents?

Thanks a lot.

**Comment by wonwill** [comment]
Thanks to your comment, I successfully got the results.
