### ISSUE TITLE
Problem while using Geo Measure Plugin

### ISSUE THREAD

**Issue by PrabuddhaBhattacharya** [lkagami/geo_measures_pymol#6]
Respected Sir

I am facing some problem with Geo Measures Plugin. I was trying to use it to carry out PCA analysis using my MD trajectory files. I had installed the required python packages using pip install pandas matplotlib scipy mdtraj sklearn. However I am getting this error every time I am trying to run the program. No results are obtained even after 24 hours of running it.

 Please find screenshots of my errors attached with this email.
 
![20230126_002905](https://user-images.githubusercontent.com/75331909/214911790-60495ad6-498e-4e28-a926-c7e6c07be725.jpg)
![20230126_002103(1)](https://user-images.githubusercontent.com/75331909/214911830-f02f2e3b-c4d5-4c13-ac7e-f4fccc3b896b.jpg)
![20230126_002145](https://user-images.githubusercontent.com/75331909/214911841-9a871508-bdc7-4e7f-833d-eb4a55b9f660.jpg)

I will be extremely grateful if you may kindly help me to resolve this problem.

Thank you,

Best Regards

**Comment by Augustus26** [comment]
Hello Prabuddha, I am also facing the same issue. Were you able to solve it? 
When there are 1000 frames in traj it works fine but I try with a merged file which has 2000 frames in it. This error comes and when I use Pymol3 updated version , application crashes on.
I even tried to make changes to script but nothing seems to work
I would really appreciate any advice you have for me

**Comment by lkagami** [comment]
Hi all, it's important to get the Pymol and python libraries from Anaconda. In addition,  when the trajectory is so large, it's possible to set a rage of time by frame in Pymol. It's will be light to RAM memory.
