### ISSUE TITLE
unable to load te files

### ISSUE THREAD

**Issue by suruchi-25** [lkagami/geo_measures_pymol#9]
when for PCA analysis tring to load the files, the error occured
 ObjectMolecule: plugin 'xtc' cannot open '/home/it-admin/Desktop/pdf/md_0_10_center.xtc'.
 Error: Could not load trajectory

can you please suggest what should i do?

**Comment by lkagami** [comment]
Dear Geo-measures user,
Did you install all needed Python packeges? 
Are you using Anaconda to run? Did you install Pymol Open-source by Anaconda? Are you using Linux or Windows OS? Thank you for use Geo-measures!!
Luciano

**Comment by suruchi-25** [comment]
yes sir i installed all the python packages needed
i am working on linux OS
yes installed it through Anaconda only

**Comment by lkagami** [comment]
Ok, please send me all error lines printed in your terminal.

**Comment by suruchi-25** [comment]
PyMOL>load_traj \
PyMOL>    /home/it-admin/Desktop/pdf/md_0_10_center.xtc, \
PyMOL>    1UNH, 1, \
PyMOL>    start=1, stop=-1, interval=1
 ObjectMolecule: plugin 'xtc' cannot open '/home/it-admin/Desktop/pdf/md_0_10_center.xtc'.
 Error: Could not load trajectory

**Comment by lkagami** [comment]
This error, is not from Geo-measures. It's a Pymol error. Read the Pymol docs and try again. I recommend that you try to use another md.pdb or md.gro and md.xtc to run. If it is OK for you, I will close this issue. Thanks!
Luciano
